# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d57a5e0201018d73004339934870da780831f29a61aeeb3a0536836c78338f901d6cf6195782ac2bc3856f540073a48ed8bba5300755f3cbdecc2e6128843434

test:
  secret_key_base: 25ef3e3b1b8608fb9223de35f4490c56e79b189c90b3006cd91620e72c55fb1da8fcc23363a75186064e7afb1736be16db2ff64bd39823eec8092be9ff1ce8ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
